### ISSUE TITLE
Unable to configure AWS ECS service deployment with x-aws-min_percent and x-aws-max_percent

### ISSUE THREAD

**Issue by lobiCode** [docker/compose-ecs#8]
**Description**

I'm trying to configure an AWS ECS service deployment using the following YAML configuration:

```yaml
services:
  foo:
    image: hello_world
    deploy:
      update_config:
        x-aws-min_percent: 0
        x-aws-max_percent: 100
```

However, it seems that the current implementation of the `ecs` package in goformation (https://github.com/awslabs/goformation/blob/master/cloudformation/ecs/aws-ecs-service_deploymentconfiguration.go#L31) includes `omitempty` on the `MinimumHealthyPercent` field, which prevents me from setting the `x-aws-min_percent` value to 0.

Is there any way to configure the AWS ECS service deployment to achieve the desired behavior? Please advise.
